### PR TITLE
Added huebutton.py, modified thebutton.py

### PR DESCRIPTION
**Pull request by kaloncheung124**
Added huebutton.py. Requires phue library to work. Also added a method
to thebutton.py that returns the corresponding xy color space for the
time remaining.

### CODE REVIEW

**Comment by ALPSquid** [comment]
Looks good! I think you might need to merge my latest changes and update the pull request; I removed the enum dependency and added a simple_colour method. I've also added an examples directory, so if you could move your example into there, that'd be awesome!

**Comment by kaloncheung124** [comment]
Sorry I didn't know how to sync with a fork. I hope this works!

**Comment by ALPSquid** [comment]
Done, had to manually merge it. Are using git on the command line? If so you should just be able to run `git pull`

**Comment by kaloncheung124** [comment]
I was just using the desktop client. Yeah sorry I know the command line
version, I should have used it.

**Pull request closed without merging**
